# Generated by Django 2.2.10 on 2020-10-03 20:43

from django.db import migrations, models
import game.validator


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201002_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='hidden_number',
            field=models.IntegerField(validators=[game.validator.validate_bigger_zero]),
        ),
    ]
