# Generated by Django 2.2.10 on 2020-10-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201003_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_master',
        ),
        migrations.AddField(
            model_name='game',
            name='game_master',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
