# Generated by Django 2.2.10 on 2020-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201004_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
